#!/bin/zsh

function zflex_clone {
	local plugin repo commitsha plugin_dir
	for plugin in $@; do
		repo="$plugin"
		clone_args=(-q --depth=1 --recursive --shallow-submodules)

		# Pin repo to a specific commit sha if provided
		if [[ "$plugin" == *'@'* ]]; then
			repo="${plugin%@*}"
			commitsha="${plugin#*@}"
			clone_args+=(--no-checkout)
		fi

		plugin_dir=$ZFLEX_PLUGIN_DIR/${repo:t}

		if [[ ! -d $plugin_dir ]]; then
			print "Cloning $repo..."
			git clone "${clone_args[@]}" https://github.com/$repo $plugin_dir

			# Change repo to a specific commit if sha is provided
			if [[ -n "$commitsha" ]]; then
				git -C $plugin_dir fetch -q origin "$commitsha"
				git -C $plugin_dir checkout -q "$commitsha"
			fi
		fi
	done
}

zflex_clone "$@"
