#!/bin/zsh

function zflex_plug {
	local plugin repo commitsha plugin_dir arg
	local plug_as plug_from
	local clone_args=(-q --depth=1 --recursive --shallow-submodules)

	# Check if "as" tag is used and return 1 if not
	if ! [[ "$@" == *'as='* ]]; then
		print -P '%F{005}Zflex: %F{001}No "%F{003}as=%F{001}" tag is found%f'
		return 1
	fi

	# Parse through tags and set their corresponding variables
	for arg in "$@"; do
		case "$arg" in
			as=*)
				case "${arg#as=}" in
					plugin|package)
						plug_as="${arg#as=}"
						;;
					*)
						print -P "%F{005}Zflex: %F{001}Invalid value of tag: %F{003}as=%F{001}${arg#as=}"
						return 1
						;;
				esac
				;;

			from=*)
				case "${arg#from=}" in
					github|gitlab|codeberg|bitbucked)
						plug_from="${arg#from=}"
						;;
					*)
						print -P "%F{005}Zflex: %F{001}Invalid value of tag: %F{003}from=%F{001}${arg#from=}"
						return 1
						;;
				esac
				;;

				# Tag to pin repo to a specific commit sha if provided
				# TODO: Add checks to know if commit sha is valid
			commit=*)
				commitsha="${arg#commit=}"
				clone_args+=(--no-checkout)
				;;

				# TODO: Remove this tmp tag later when adding non git support
			clone_args=*)
				clone_args+=("${arg#clone_args=}")
				;;
		esac
	done

	# Start cloning using values of tags parsed above
	case "$plug_as" in
		plugin)
			for plugin in "${@%as=*}"; do
				repo="$plugin"

				plugin_dir=$ZFLEX_PLUGIN_DIR/${repo:t}

				# Check if given plugin have been cloned already
				if [[ ! -d $plugin_dir ]]; then
					print "%F{005}Zflex: %F{003}Cloning %F{004}$repo...%f"

					# Clone from destination chosen in $plug_from
					case "$plug_from" in
						github|gitlab|bitbucked)
							git clone "${clone_args[@]}" https://$plug_from.com/$repo $plugin_dir
							;;
						codeberg)
							git clone "${clone_args[@]}" https://$plug_from.org/$repo $plugin_dir
							;;
					esac

					# Pin repo to specific commit sha if it is provided and
					# only one repo have been passed
					if [[ -n "$commitsha" ]] && [[ -n $foo ]]; then
						git -C $plugin_dir fetch -q origin "$commitsha"
						git -C $plugin_dir checkout -q "$commitsha"
					fi
				fi
			done
			;;
		package)
			print 'Using "as=package" is not implemented yet'
			;;
	esac
}

zflex_plug "$@"
