#!/bin/zsh

function zflex_update {
	case "$1" in
		-i)
			local d
			for d in $ZFLEX_PLUGIN_DIR/*/.git(/); do
				print -n "Update ${d:h:t}? [y/n]: "
				read -rsq &> /dev/null && git -C "${d:h}" pull --ff --recurse-submodules --depth=1 --rebase --autostash
			done
			;;
		*)
			local d
			for d in $ZFLEX_PLUGIN_DIR/*/.git(/); do
				echo "Updating ${d:h:t}..."
				git -C "${d:h}" pull --ff --recurse-submodules --depth=1 --rebase --autostash
			done
			;;
	esac
}

zflex_update "$@"
