#!/bin/zsh

# Function used for "update" subcommand of zflex
function zflex_update {
	local plugin confirmation

	# Check if first arg is one of the options like -i or -q
	case "$1" in
		-q)
			shift
			# Check if user gave anything after option so we can update
			# only plugins given by user or update all currently available plugins otherwise
			if (( $#@ )); then
				for plugin in "$ZFLEX_PLUGIN_DIR/$@/"; do
					git -C "$plugin" pull --ff --recurse-submodules --depth=1 --rebase --autostash &> /dev/null &
				done
				wait
			else
				for plugin in $ZFLEX_PLUGIN_DIR/*/; do
					git -C "$plugin" pull --ff --recurse-submodules --depth=1 --rebase --autostash &> /dev/null &
				done
				wait
			fi
			return
			;;
		-i)
			shift
			# Check if user gave anything after option so we can ask to update
			# only plugins given by user or ask to update all currently available plugins otherwise
			if (( $#@ )); then
				for plugin in $ZFLEX_PLUGIN_DIR/$@/; do
					# Confirm before updating any of plugins
					print -n "Update ${plugin:t}? (Y)es/(n)o/(a)lways: "
					read -r confirmation
					case "$confirmation" in
						a|A)
							# Update all currently available plugins in parallel
							print "Updating all plugins in parallel..."
							for plugin in $ZFLEX_PLUGIN_DIR/$@/; do
								git -C "$plugin" pull --ff --recurse-submodules --depth=1 --rebase --autostash || print "Couldn't update ${plugin:t}" &
							done
							wait
							print "Finished updating"
							return
							;;
						y|Y|'')
							print "Updating ${plugin:t}..."
							git -C "$plugin" pull --ff --recurse-submodules --depth=1 --rebase --autostash || print "Couldn't update ${plugin:t}"
							;;
						n|N|*)
							print "Skipped ${plugin:t}"
							;;
					esac
				done
				return
			else
				for plugin in $ZFLEX_PLUGIN_DIR/*/.git(/); do
					# Confirm before updating any of plugins
					print -n "Update ${plugin:h:t}? (Y)es/(n)o/(a)lways: "
					read -r confirmation
					case "$confirmation" in
						a|A)
							# Update all currently available plugins in parallel
							print "Updating all plugins in parallel..."
							for plugin in $ZFLEX_PLUGIN_DIR/*/.git(/); do
								git -C "${plugin:h}" pull --ff --recurse-submodules --depth=1 --rebase --autostash || print "Couldn't update ${plugin:t}" &
							done
							wait
							print "Finished updating"
							return
							;;
						y|Y|'')
							print "Updating ${plugin:h:t}..."
							git -C "${plugin:h}" pull --ff --recurse-submodules --depth=1 --rebase --autostash || print "Couldn't update ${plugin:t}"
							;;
						n|N|*)
							print "Skipped ${plugin:h:t}"
							;;
					esac
				done
				return
			fi
			;;
	esac

	# If no options were used just update all plugins in parallel
	print "Updating all plugins in parallel..."
	for plugin in $ZFLEX_PLUGIN_DIR/*/.git(/); do
		git -C "${plugin:h}" pull --ff --recurse-submodules --depth=1 --rebase --autostash || print "Couldn't update ${plugin:h:t}"
	done
	wait
}

zflex_update "$@"
